#!/usr/bin/env python3
"""Cleanup."""


import os
import sys
from typing import List
import logging
import argparse
import pathlib


log = logging.getLogger()


def check_dirs(dir_names: List[str]) -> None:
    """Check if directories can be cleaned."""


def clean(dir_names: List[str]) -> None:
    """Clean."""


def main() -> int:
    """Main."""

    # Setup.

    log.setLevel(logging.DEBUG)

    arg_parser = argparse.ArgumentParser(prog=pathlib.PurePosixPath(__file__).stem,
                                         description=sys.modules[__name__].__doc__,
                                         epilog="Source file directory can't be cleaned.",
                                         formatter_class=argparse.MetavarTypeHelpFormatter)
    arg_parser.add_argument("dir_names", type=str, nargs="*",
                            help="Directory names.")
    args = arg_parser.parse_args()

    # Program.

    check_dirs(args.dir_names)
    clean(args.dir_names)

    # Teardown.

    log.handlers.clear()

    return 0


if __name__ == "__main__":
    sys.exit(main)
